special_tokens:
    "START": 0 # 1 for gpt2, 0 for bart
    "END": 2
    "UNK": 3
    "SEP": 4
    "EXPAND": 5
    "MASK": 6
    "(": 10
    ")": 11
    "e": 13
    "p": 14
    "i": 15
    "u": 16
    "n": 17
offset: 100
ans_len: 32
qry_len: 10
act_max_var: 16