
dreamon:
  nepoch: 500
  lr: 1e-4
  warm_up: 5
  weight_decay: 1e-5
  batch_size: 2
gpt2:
  nepoch: 100
  lr: 5e-5
  warm_up: 25
  weight_decay: 1e-6
  batch_size: 1024

mydream:
  nepoch: 200
  lr: 1e-4
  warm_up: 25
  weight_decay: 1e-6
  batch_size: 256